import uuid
from typing import List, Optional
from pydantic import BaseModel, Field, field_validator


class RAGSourceChunk(BaseModel):
    """
    Metadata and text for a document chunk used as context for the RAG answer.
    Note: Does NOT expose raw embedding vectors.
    """
    id: str = Field(description="Unique UUID of the chunk record")
    document_id: str = Field(description="UUID of the parent document")
    chunk_index: int = Field(ge=0, description="Sequential position of chunk within the document")
    content: str = Field(description="Extracted text content of the chunk")
    start_char: int = Field(ge=0, description="Character start offset in original document")
    end_char: int = Field(ge=0, description="Character end offset in original document")
    similarity: float = Field(description="Cosine similarity score (higher = closer match)")

    model_config = {
        "json_schema_extra": {
            "example": {
                "id": "123e4567-e89b-12d3-a456-426614174000",
                "document_id": "987fcdeb-51a2-43f1-b890-123456789abc",
                "chunk_index": 0,
                "content": "5 years of experience in accessible web development using React and WCAG guidelines...",
                "start_char": 0,
                "end_char": 450,
                "similarity": 0.892,
            }
        }
    }


class RAGRequest(BaseModel):
    """
    Request payload for asking a question answered via RAG over uploaded documents.
    """
    question: str = Field(..., min_length=1, description="Natural language question to ask about the documents")
    document_id: Optional[str] = Field(default=None, description="Optional UUID to restrict retrieval to a specific document")
    limit: int = Field(default=5, ge=1, le=20, description="Maximum number of context chunks to retrieve (1-20)")

    @field_validator("question")
    @classmethod
    def validate_question(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Question cannot be empty or whitespace only.")
        return v.strip()

    @field_validator("document_id")
    @classmethod
    def validate_document_id(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and v.strip():
            clean_id = v.strip()
            try:
                uuid.UUID(clean_id)
                return clean_id
            except (ValueError, TypeError):
                raise ValueError(f"document_id must be a valid UUID string, got: '{clean_id}'")
        return None

    model_config = {
        "json_schema_extra": {
            "example": {
                "question": "What assistive technologies and accessibility tools does the candidate have experience with?",
                "document_id": "987fcdeb-51a2-43f1-b890-123456789abc",
                "limit": 5,
            }
        }
    }


class RAGResponse(BaseModel):
    """
    Response payload containing the question, grounded answer, and supporting source chunks.
    """
    question: str = Field(description="The submitted question")
    answer: str = Field(description="The grounded answer generated by Gemini from document context")
    sources: List[RAGSourceChunk] = Field(default_factory=list, description="Document chunks used as grounding context")
    has_context: bool = Field(description="Whether relevant document context was found to ground the answer")

    model_config = {
        "json_schema_extra": {
            "example": {
                "question": "What assistive technologies does the candidate know?",
                "answer": "Based on the provided documents, the candidate has experience with NVDA, JAWS screen readers, and VoiceOver.",
                "sources": [
                    {
                        "id": "123e4567-e89b-12d3-a456-426614174000",
                        "document_id": "987fcdeb-51a2-43f1-b890-123456789abc",
                        "chunk_index": 0,
                        "content": "Proficient in testing with NVDA, JAWS screen readers, and Apple VoiceOver...",
                        "start_char": 0,
                        "end_char": 350,
                        "similarity": 0.887,
                    }
                ],
                "has_context": True,
            }
        }
    }
